// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-food-logs.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function requireAuth(ctx) {
  return ctx.isAuthenticated() && ctx.getUserId() ? null : { content: [{ type: "text", text: "Not authenticated." }], isError: true };
}

// src/lib/mcp/tools/list-food-logs.ts
var list_food_logs_default = defineTool({
  name: "list_food_logs",
  title: "List food logs",
  description: "List the signed-in user's most recent food log entries, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("How many entries to return."),
    since: z.string().optional().describe("Optional ISO date/time; only entries created after it are returned.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, since }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    let query = supabaseForUser(ctx).from("food_logs").select("id, food_name, description, created_at, analysis_result").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (since) query = query.gte("created_at", since);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { logs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-food-log.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var add_food_log_default = defineTool2({
  name: "add_food_log",
  title: "Add food log",
  description: "Record a meal or food item for the signed-in user.",
  inputSchema: {
    food_name: z2.string().trim().min(1).describe("Name of the meal or food item."),
    description: z2.string().trim().optional().describe("Optional notes about the meal."),
    created_at: z2.string().optional().describe("Optional ISO timestamp for backdated entries.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ food_name, description, created_at }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const { data, error } = await supabaseForUser(ctx).from("food_logs").insert({ user_id: ctx.getUserId(), food_name, description, ...created_at ? { created_at } : {} }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { log: data } };
  }
});

// src/lib/mcp/tools/list-stool-logs.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_stool_logs_default = defineTool3({
  name: "list_stool_logs",
  title: "List stool logs",
  description: "List the signed-in user's most recent stool entries (Bristol type, colour, consistency), newest first.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).default(20).describe("How many entries to return."),
    since: z3.string().optional().describe("Optional ISO date/time; only entries created after it are returned.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, since }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    let query = supabaseForUser(ctx).from("stool_logs").select("id, bristol_type, color, consistency, notes, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (since) query = query.gte("created_at", since);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { logs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-stool-log.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var add_stool_log_default = defineTool4({
  name: "add_stool_log",
  title: "Add stool log",
  description: "Record a stool entry for the signed-in user.",
  inputSchema: {
    bristol_type: z4.number().int().min(1).max(7).optional().describe("Bristol stool scale type, 1-7."),
    color: z4.string().trim().optional().describe("Colour, e.g. brown, green, black."),
    consistency: z4.string().trim().optional().describe("Consistency description."),
    notes: z4.string().trim().optional().describe("Optional notes."),
    created_at: z4.string().optional().describe("Optional ISO timestamp for backdated entries.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ bristol_type, color, consistency, notes, created_at }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const { data, error } = await supabaseForUser(ctx).from("stool_logs").insert({
      user_id: ctx.getUserId(),
      bristol_type,
      color,
      consistency,
      notes,
      ...created_at ? { created_at } : {}
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { log: data } };
  }
});

// src/lib/mcp/tools/list-wellness-logs.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_wellness_logs_default = defineTool5({
  name: "list_wellness_logs",
  title: "List wellness logs",
  description: "List the signed-in user's daily wellness check-ins (sleep, stress, water, exercise), newest first.",
  inputSchema: {
    limit: z5.number().int().min(1).max(100).default(14).describe("How many entries to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const { data, error } = await supabaseForUser(ctx).from("wellness_logs").select("id, sleep_hours, stress_level, water_glasses, exercise_minutes, wellness_score, notes, created_at").order("created_at", { ascending: false }).limit(limit ?? 14);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { logs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-health-profile.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_health_profile_default = defineTool6({
  name: "get_health_profile",
  title: "Get health profile",
  description: "Read the signed-in user's gut health profile: age, diet, restrictions, conditions, medications.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const { data, error } = await supabaseForUser(ctx).from("user_health_profiles").select("*").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}) }],
      structuredContent: { profile: data ?? null }
    };
  }
});

// src/lib/mcp/tools/list-test-results.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var list_test_results_default = defineTool7({
  name: "list_test_results",
  title: "List test results",
  description: "List the signed-in user's uploaded lab/test result summaries, newest first.",
  inputSchema: {
    limit: z6.number().int().min(1).max(50).default(10).describe("How many results to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const { data, error } = await supabaseForUser(ctx).from("test_results").select("id, file_name, test_type, summary, key_findings, recommendations, concern_level, created_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ppfonjpfpyfeklecowpd";
var mcp_default = defineMcp({
  name: "gutlyhealth",
  title: "gutlyhealth",
  version: "0.1.0",
  instructions: "Tools for Gutly, a gut health tracker. Read and add the signed-in user's food logs, stool logs, and wellness check-ins, and read their health profile and lab test summaries. Use this data to answer questions about digestive patterns; it is personal health data, so never share it outside the conversation.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_food_logs_default,
    add_food_log_default,
    list_stool_logs_default,
    add_stool_log_default,
    list_wellness_logs_default,
    get_health_profile_default,
    list_test_results_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
