// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpfusmytujopvfyebiar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwZnVzbXl0dWpvcHZmeWViaWFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDI5MTUsImV4cCI6MjA2NjAxODkxNX0.bG6uh0CGA5pEC156LDalndJ6GSsv-jwRu13cELz5arg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);